export enum SCREEN_NAMES {
  BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR',
  HOME = 'Home',
  PREVENTION = 'Prevention',
  SYMPTOMS_CHECKER = 'SYMPTOMS_CHECKER',
  PREDICTION = 'Prediction',
  TREATMENT = 'Treatment',

  QUESTIONS = 'QUESTIONS',
  SYMPTOMS_CHECKER_WELCOME = 'Welcome',

  MAP = 'MAP',
  PROBABILITY = 'PROBABILITY',
}
