export enum SCREEN_NAMES {
  BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR',
  HOME = 'HOME',
  PREVENTION = 'PREVENTION',
  SYMPTOMS_CHECKER = 'SYMPTOMS_CHECKER',
  PREDICTION = 'PREDICTION',
  QUESTIONS = 'QUESTIONS',
  MAP = 'MAP',
  PROBABILITY = 'PROBABILITY',
}
